-- PRE-F5C executable/physical reconciliation; approved by DR-PRE-F5C-2026-09-21-005.
-- Forward-only rollback is operational backup/restore; no destructive down migration is authorized.
DO $$
DECLARE ledger_rows integer; physical_rows integer;
BEGIN
  SELECT count(*) INTO ledger_rows FROM platform.schema_migrations WHERE outcome = 'applied';
  IF ledger_rows <> 10 OR NOT EXISTS (SELECT 1 FROM platform.schema_migrations WHERE migration_id = '20260916001000') THEN
    RAISE EXCEPTION 'PRE_F5C_PREFLIGHT_LEDGER_EXPECTED_10_APPLIED';
  END IF;
  SELECT count(*) INTO physical_rows FROM pg_catalog.pg_tables WHERE schemaname IN ('platform', 'iam', 'org', 'regulatory', 'controls', 'evidence', 'remediation', 'risk', 'audit', 'operations', 'third_party', 'resilience', 'privacy', 'survey', 'data', 'config', 'rules', 'integration', 'reporting', 'knowledge', 'ai', 'notification', 'ops_audit') AND NOT (schemaname = 'platform' AND tablename = 'schema_migrations');
  IF physical_rows <> 229 THEN RAISE EXCEPTION 'PRE_F5C_PREFLIGHT_EXPECTED_229_TABLES'; END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'regulatory' AND table_name = 'requirement_applicabilities' AND column_name = 'row_version') THEN
    RAISE EXCEPTION 'PRE_F5C_PREFLIGHT_ALREADY_MATERIALIZED';
  END IF;
END $$;

ALTER TABLE "regulatory"."requirement_applicabilities" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "regulatory"."requirement_applicabilities" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "regulatory"."requirement_applicabilities" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "regulatory"."requirement_applicabilities" ADD CONSTRAINT "ck_requirement_applicabilities__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_requirement_applicabilities__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "regulatory"."requirement_applicabilities" ADD CONSTRAINT "fk_requirement_applicabilities__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_requirement_applicabilities__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "regulatory"."requirement_assessments" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "regulatory"."requirement_assessments" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "regulatory"."requirement_assessments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "regulatory"."requirement_assessments" ADD CONSTRAINT "ck_requirement_assessments__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_requirement_assessments__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "regulatory"."requirement_assessments" ADD CONSTRAINT "fk_requirement_assessments__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_requirement_assessments__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "regulatory"."statements_of_applicability" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "regulatory"."statements_of_applicability" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "regulatory"."statements_of_applicability" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "regulatory"."statements_of_applicability" ADD CONSTRAINT "ck_statements_of_applicability__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_statements_of_applicability__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "regulatory"."statements_of_applicability" ADD CONSTRAINT "fk_statements_of_applicability__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_statements_of_applicability__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "controls"."control_assessments" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "controls"."control_assessments" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "controls"."control_assessments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "controls"."control_assessments" ADD CONSTRAINT "ck_control_assessments__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_control_assessments__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "controls"."control_assessments" ADD CONSTRAINT "fk_control_assessments__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_control_assessments__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "controls"."assurance_tests" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "controls"."assurance_tests" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "controls"."assurance_tests" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "controls"."assurance_tests" ADD CONSTRAINT "ck_assurance_tests__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_assurance_tests__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "controls"."assurance_tests" ADD CONSTRAINT "fk_assurance_tests__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_assurance_tests__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "evidence"."evidence_versions" ADD COLUMN "updated_at" timestamptz, ADD COLUMN "updated_by_user_identity_id" uuid, ADD COLUMN "updated_by_service_principal_id" uuid, ADD COLUMN "row_version" bigint NOT NULL DEFAULT 1;
UPDATE "evidence"."evidence_versions" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;
ALTER TABLE "evidence"."evidence_versions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE "evidence"."evidence_versions" ADD CONSTRAINT "ck_evidence_versions__updated_actor_one" CHECK (num_nonnulls(updated_by_user_identity_id, updated_by_service_principal_id) <= 1), ADD CONSTRAINT "ck_evidence_versions__row_version_positive" CHECK (row_version > 0);
ALTER TABLE "evidence"."evidence_versions" ADD CONSTRAINT "fk_evidence_versions__updated_by_user_identity_id" FOREIGN KEY ("updated_by_user_identity_id") REFERENCES "iam"."user_identities" ("user_identity_id") ON UPDATE NO ACTION ON DELETE RESTRICT, ADD CONSTRAINT "fk_evidence_versions__updated_by_service_principal_id" FOREIGN KEY ("updated_by_service_principal_id") REFERENCES "iam"."service_principals" ("service_principal_id") ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE "regulatory"."requirement_applicabilities" ADD COLUMN "superseded_by_id" uuid;
ALTER TABLE "regulatory"."requirement_applicabilities" DROP CONSTRAINT "uq_requirement_applicabilities__tenant_id_requirement__c645d089";
ALTER TABLE "regulatory"."requirement_applicabilities" ADD CONSTRAINT "uq_requirement_applicabilities__tenant_id_requirement__cf3910e1" UNIQUE NULLS NOT DISTINCT ("tenant_id", "requirement_id", "scope_subject_id", "applicability_version");
ALTER TABLE "regulatory"."requirement_applicabilities" ADD CONSTRAINT "fk_requirement_applicabilities__superseded_by_id" FOREIGN KEY ("tenant_id", "superseded_by_id") REFERENCES "regulatory"."requirement_applicabilities" ("tenant_id", "requirement_applicability_id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "regulatory"."statements_of_applicability" DROP CONSTRAINT "uq_statements_of_applicability__tenant_id_soa_version";
ALTER TABLE "regulatory"."statements_of_applicability" ADD CONSTRAINT "uq_statements_of_applicability__tenant_id_framework_ve_11f60c98" UNIQUE NULLS NOT DISTINCT ("tenant_id", "framework_version_id", "soa_version");
ALTER TABLE "regulatory"."statement_of_applicability_items" ADD CONSTRAINT "uq_statement_of_applicability_items__tenant_id_stateme_9e536872" UNIQUE NULLS NOT DISTINCT ("tenant_id", "statement_of_applicability_id", "reference_control_version_id");
ALTER TABLE "evidence"."evidence_versions" ADD CONSTRAINT "uq_evidence_versions__tenant_id_evidence_id_version_number" UNIQUE NULLS NOT DISTINCT ("tenant_id", "evidence_id", "version_number");

INSERT INTO iam.permissions (permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, updated_at, updated_by_user_identity_id, updated_by_service_principal_id, row_version, permission_code, domain_code, resource_code, action_code, lifecycle_state) VALUES ('01a0c143-2c00-72e4-ad85-308cca2eb2f5', '2026-09-21T00:00:00.000Z', NULL, NULL, '2026-09-21T00:00:00.000Z', NULL, NULL, 1, 'compliance.soa.create', 'compliance', 'soa', 'create', 'published') ON CONFLICT (permission_code) DO NOTHING;
INSERT INTO iam.role_permissions (role_permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, ownership_class, tenant_id, role_id, permission_id) SELECT '01a0c143-2c00-7012-a567-ccf05fb305fd', '2026-09-21T00:00:00.000Z', NULL, NULL, 'PLATFORM_CONTROL', NULL, r.role_id, p.permission_id FROM iam.roles r CROSS JOIN iam.permissions p WHERE r.role_code = 'GRC_MANAGER' AND r.tenant_id IS NULL AND p.permission_code = 'compliance.soa.create' ON CONFLICT DO NOTHING;
INSERT INTO iam.role_permissions (role_permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, ownership_class, tenant_id, role_id, permission_id) SELECT '01a0c143-2c00-76f5-a56b-6f0e6e9746d9', '2026-09-21T00:00:00.000Z', NULL, NULL, 'PLATFORM_CONTROL', NULL, r.role_id, p.permission_id FROM iam.roles r CROSS JOIN iam.permissions p WHERE r.role_code = 'COMPLIANCE_MANAGER' AND r.tenant_id IS NULL AND p.permission_code = 'compliance.soa.create' ON CONFLICT DO NOTHING;
INSERT INTO iam.permissions (permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, updated_at, updated_by_user_identity_id, updated_by_service_principal_id, row_version, permission_code, domain_code, resource_code, action_code, lifecycle_state) VALUES ('01a0c143-2c00-71f9-a2c9-c043f4bdbebe', '2026-09-21T00:00:00.000Z', NULL, NULL, '2026-09-21T00:00:00.000Z', NULL, NULL, 1, 'controls.assurance_test.create', 'controls', 'assurance_test', 'create', 'published') ON CONFLICT (permission_code) DO NOTHING;
INSERT INTO iam.role_permissions (role_permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, ownership_class, tenant_id, role_id, permission_id) SELECT '01a0c143-2c00-7687-80fc-f646ec0e67e1', '2026-09-21T00:00:00.000Z', NULL, NULL, 'PLATFORM_CONTROL', NULL, r.role_id, p.permission_id FROM iam.roles r CROSS JOIN iam.permissions p WHERE r.role_code = 'GRC_MANAGER' AND r.tenant_id IS NULL AND p.permission_code = 'controls.assurance_test.create' ON CONFLICT DO NOTHING;
INSERT INTO iam.role_permissions (role_permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, ownership_class, tenant_id, role_id, permission_id) SELECT '01a0c143-2c00-7433-8106-2b09dd0950df', '2026-09-21T00:00:00.000Z', NULL, NULL, 'PLATFORM_CONTROL', NULL, r.role_id, p.permission_id FROM iam.roles r CROSS JOIN iam.permissions p WHERE r.role_code = 'AUDITOR_LEAD' AND r.tenant_id IS NULL AND p.permission_code = 'controls.assurance_test.create' ON CONFLICT DO NOTHING;
INSERT INTO iam.role_permissions (role_permission_id, created_at, created_by_user_identity_id, created_by_service_principal_id, ownership_class, tenant_id, role_id, permission_id) SELECT '01a0c143-2c00-7fa9-8e6a-3d0854d1da94', '2026-09-21T00:00:00.000Z', NULL, NULL, 'PLATFORM_CONTROL', NULL, r.role_id, p.permission_id FROM iam.roles r CROSS JOIN iam.permissions p WHERE r.role_code = 'AUDITOR' AND r.tenant_id IS NULL AND p.permission_code = 'controls.assurance_test.create' ON CONFLICT DO NOTHING;

INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-724c-a98c-e1aef8feaa1b', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementApplicability', 1, 'draft', 'applicability.submit', 'submitted', 'contract:transition:RequirementApplicability:draft:applicability.submit:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.applicability.submit.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.applicability.submit' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7427-9362-036ac3594f36', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-724c-a98c-e1aef8feaa1b', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-78a4-97f4-b6fca8f60597', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-724c-a98c-e1aef8feaa1b', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-75eb-b3b2-30fa6cf1e2c0', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-724c-a98c-e1aef8feaa1b', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-78fd-a23e-3dfee9291d97', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-724c-a98c-e1aef8feaa1b', 'compliance.applicability.submitted.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-743f-ad18-9cb199833f68', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementApplicability', 1, 'submitted', 'applicability.approve', 'approved', 'contract:transition:RequirementApplicability:submitted:applicability.approve:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.applicability.approve.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.applicability.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-76a2-8349-25e03f1e5d4c', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-743f-ad18-9cb199833f68', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7635-a698-5c9d38b6fc41', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-743f-ad18-9cb199833f68', 'compliance.applicability.approved.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7ef5-9490-b09680b7c9d1', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementApplicability', 1, 'approved', 'applicability.supersede', 'superseded', 'contract:transition:RequirementApplicability:approved:applicability.supersede:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.lifecycle.applicability.supersede.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.applicability.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7ffb-a41b-2e3c15180f8f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7ef5-9490-b09680b7c9d1', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-76d8-b83b-6e46f5449047', '2026-09-21T00:00:00.000Z', NULL, NULL, 'StatementOfApplicability', 1, 'draft', 'soa.publish', 'published', 'contract:transition:StatementOfApplicability:draft:soa.publish:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.soa.publish.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.soa.publish' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7e51-8550-32422eefc109', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-76d8-b83b-6e46f5449047', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7acb-b694-119316de788b', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-76d8-b83b-6e46f5449047', 'compliance.soa.published.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-780e-819f-65e8b8e9f1cb', '2026-09-21T00:00:00.000Z', NULL, NULL, 'StatementOfApplicability', 1, 'published', 'soa.supersede', 'superseded', 'contract:transition:StatementOfApplicability:published:soa.supersede:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.lifecycle.soa.supersede.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.soa.publish' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7df5-aa9e-537eb4dd9a80', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-780e-819f-65e8b8e9f1cb', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7e85-a70c-1d0d268503b2', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'draft', 'evidence.submit', 'submitted', 'contract:transition:EvidenceVersion:draft:evidence.submit:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.evidence.evidence.submit.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.submit' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7b08-87ca-811fc5b8426b', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e85-a70c-1d0d268503b2', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-741e-8016-eb0167c6db8a', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e85-a70c-1d0d268503b2', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7432-8a24-e1450ab5a9dc', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e85-a70c-1d0d268503b2', 'evidence.evidence.submitted.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7d51-bb6c-2ce4f50cc1e6', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'submitted', 'evidence.start_review', 'under_review', 'contract:transition:EvidenceVersion:submitted:evidence.start_review:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.evidence.evidence.start_review.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.review' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-77d0-959f-d9acc5e8d62f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d51-bb6c-2ce4f50cc1e6', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-76e1-a80c-70b03c7ad7a3', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d51-bb6c-2ce4f50cc1e6', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-794a-9663-3cc010d5c49f', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'under_review', 'evidence.approve', 'approved', 'contract:transition:EvidenceVersion:under_review:evidence.approve:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.evidence.evidence.approve.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7e7a-9f81-8d378a1e4715', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-794a-9663-3cc010d5c49f', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7cce-b717-b895c7549f44', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-794a-9663-3cc010d5c49f', 'evidence.evidence.approved.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7c7d-9002-5b7bde8ae11c', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'under_review', 'evidence.reject', 'rejected', 'contract:transition:EvidenceVersion:under_review:evidence.reject:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.evidence.evidence.reject.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.reject' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-70e7-a66f-5403d088dbad', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7c7d-9002-5b7bde8ae11c', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7f63-9a63-9c73534205e3', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7c7d-9002-5b7bde8ae11c', 'evidence.evidence.rejected.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7e60-b8f5-d6cbd1c8a371', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'approved', 'evidence.expire', 'expired', 'contract:transition:EvidenceVersion:approved:evidence.expire:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.lifecycle.evidence.expire.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.archive' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7fa3-86b0-cda66ac50dc9', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e60-b8f5-d6cbd1c8a371', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7a56-95f0-fa570e6b058f', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'approved', 'evidence.supersede', 'superseded', 'contract:transition:EvidenceVersion:approved:evidence.supersede:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.lifecycle.evidence.supersede.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.archive' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-74c2-ae18-cad08eb225e8', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7a56-95f0-fa570e6b058f', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7b17-b623-a6647c1f0aa8', '2026-09-21T00:00:00.000Z', NULL, NULL, 'EvidenceVersion', 1, 'rejected', 'evidence.revise', 'draft', 'contract:transition:EvidenceVersion:rejected:evidence.revise:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.lifecycle.evidence.revise.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'evidence.evidence.update' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7509-8e73-ba61e04e0214', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7b17-b623-a6647c1f0aa8', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7d29-961f-c51de5e54946', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7b17-b623-a6647c1f0aa8', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7d3a-9e91-a758b3454a43', '2026-09-21T00:00:00.000Z', NULL, NULL, 'AssuranceTest', 1, 'in_progress', 'assurance_test.execute', 'completed', 'contract:transition:AssuranceTest:in_progress:assurance_test.execute:v1', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.assurance_test.execute.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.assurance_test.execute' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7e61-bfef-56e8622967b7', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d3a-9e91-a758b3454a43', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-798e-9384-8a50f805dd9d', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d3a-9e91-a758b3454a43', 'audit_engagement') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7eda-8420-601a56f7c274', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d3a-9e91-a758b3454a43', 'controls.assurance_test.completed.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7d85-9e16-c4efce4fa039', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementAssessment', 2, 'not_assessed', 'requirement_assessment.start', 'in_progress', 'contract:transition:RequirementAssessment:not_assessed:requirement_assessment.start:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.requirement_assessment.start.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.requirement_assessment.update' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7cee-bd8d-d0b3c034392d', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d85-9e16-c4efce4fa039', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7500-aba3-abfc3c112d5f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d85-9e16-c4efce4fa039', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7b8c-a910-a597e52ba82f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7d85-9e16-c4efce4fa039', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-74a9-a5b6-3b7906d0dbf8', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementAssessment', 2, 'in_progress', 'requirement_assessment.submit', 'assessed', 'contract:transition:RequirementAssessment:in_progress:requirement_assessment.submit:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.requirement_assessment.submit.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.requirement_assessment.submit' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-711d-b59c-e088fbda7281', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-74a9-a5b6-3b7906d0dbf8', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7104-aba6-8fe8ee5f50bf', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-74a9-a5b6-3b7906d0dbf8', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7db6-ad7e-b169f5849893', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-74a9-a5b6-3b7906d0dbf8', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7748-aabb-f3d56309731f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-74a9-a5b6-3b7906d0dbf8', 'compliance.requirement_assessment.assessed.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7f80-86c6-05b2582a555f', '2026-09-21T00:00:00.000Z', NULL, NULL, 'RequirementAssessment', 2, 'assessed', 'requirement_assessment.approve', 'approved', 'contract:transition:RequirementAssessment:assessed:requirement_assessment.approve:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.compliance.requirement_assessment.approve.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'compliance.requirement_assessment.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-772a-a7f5-f9f38302cc75', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7f80-86c6-05b2582a555f', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7702-b8c7-6cbb3c7b79ba', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7f80-86c6-05b2582a555f', 'compliance.requirement_assessment.approved.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7770-88a7-07c1c92ec69d', '2026-09-21T00:00:00.000Z', NULL, NULL, 'ControlAssessment', 2, 'planned', 'control_assessment.start', 'in_progress', 'contract:transition:ControlAssessment:planned:control_assessment.start:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.control_assessment.start.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.control_assessment.update' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7992-8c10-85f2c10e8bd8', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7770-88a7-07c1c92ec69d', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-78e0-b2cb-edc45f655f0a', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7770-88a7-07c1c92ec69d', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-77b6-af31-c75172774908', '2026-09-21T00:00:00.000Z', NULL, NULL, 'ControlAssessment', 2, 'in_progress', 'control_assessment.complete', 'completed', 'contract:transition:ControlAssessment:in_progress:control_assessment.complete:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.control_assessment.complete.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.control_assessment.submit' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7708-aa4f-2197c70f609f', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b6-af31-c75172774908', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-78ed-a794-a6cc8620a922', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b6-af31-c75172774908', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-71b1-ac45-af4f09e82050', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b6-af31-c75172774908', 'controls.control_assessment.completed.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7ed1-84c5-afdd47864fdb', '2026-09-21T00:00:00.000Z', NULL, NULL, 'ControlAssessment', 2, 'completed', 'control_assessment.review', 'reviewed', 'contract:transition:ControlAssessment:completed:control_assessment.review:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.control_assessment.review.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.control_assessment.review' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7e6d-af6a-c28750a82da5', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7ed1-84c5-afdd47864fdb', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-70f8-8f4d-6fbc5593a7c0', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7ed1-84c5-afdd47864fdb', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-72d2-825c-0aabd636e6e5', '2026-09-21T00:00:00.000Z', NULL, NULL, 'ControlAssessment', 2, 'reviewed', 'control_assessment.approve', 'approved', 'contract:transition:ControlAssessment:reviewed:control_assessment.approve:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.control_assessment.approve.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.control_assessment.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7392-92b7-58ac787911eb', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-72d2-825c-0aabd636e6e5', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7121-9d52-95617247c4e2', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-72d2-825c-0aabd636e6e5', 'controls.control_assessment.approved.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-77fc-9552-c91866a89af1', '2026-09-21T00:00:00.000Z', NULL, NULL, 'AssuranceTest', 2, 'planned', 'assurance_test.start', 'in_progress', 'contract:transition:AssuranceTest:planned:assurance_test.start:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.assurance_test.start.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.assurance_test.execute' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-757f-968e-0c422439347c', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77fc-9552-c91866a89af1', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7039-aa1c-0ba365b00701', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77fc-9552-c91866a89af1', 'audit_engagement') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-70cb-81e8-c097ad1aac12', '2026-09-21T00:00:00.000Z', NULL, NULL, 'AssuranceTest', 2, 'completed', 'assurance_test.review', 'reviewed', 'contract:transition:AssuranceTest:completed:assurance_test.review:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.assurance_test.review.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.assurance_test.review' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7f16-a411-ec5c1b50b8e4', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-70cb-81e8-c097ad1aac12', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-75f0-bc70-abf4eb2776ff', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-70cb-81e8-c097ad1aac12', 'audit_engagement') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7127-92ca-e57346465135', '2026-09-21T00:00:00.000Z', NULL, NULL, 'AssuranceTest', 2, 'reviewed', 'assurance_test.approve', 'approved', 'contract:transition:AssuranceTest:reviewed:assurance_test.approve:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.controls.assurance_test.approve.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'controls.assurance_test.approve' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7265-ae2a-bc164ee1dd44', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7127-92ca-e57346465135', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7a10-a74e-b72bd9cece72', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Issue', 2, 'open', 'issue.triage', 'triaged', 'contract:transition:Issue:open:issue.triage:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.issue.triage.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.issue.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7ba1-aaae-7bc081a025b4', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7a10-a74e-b72bd9cece72', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-742d-889d-0e60c205d583', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7a10-a74e-b72bd9cece72', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7163-8c41-cc1072aa5ecb', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7a10-a74e-b72bd9cece72', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-7ff8-9a07-cf9f0ba1a8fa', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7a10-a74e-b72bd9cece72', 'remediation.issue.triaged.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7f36-a557-13473c657db5', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Issue', 2, 'triaged', 'issue.start_remediation', 'remediation_in_progress', 'contract:transition:Issue:triaged:issue.start_remediation:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.issue.start_remediation.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.issue.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-79df-8072-feb1aab33dc8', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7f36-a557-13473c657db5', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7986-9fdc-8de6d73934ea', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7f36-a557-13473c657db5', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7c4a-b386-70d76b53de4b', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7f36-a557-13473c657db5', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7685-8f4a-955a644fa130', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Issue', 2, 'remediation_in_progress', 'issue.request_verification', 'pending_verification', 'contract:transition:Issue:remediation_in_progress:issue.request_verification:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.issue.request_verification.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.issue.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-78b4-9411-1d9c287cfb5d', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7685-8f4a-955a644fa130', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-77bb-94e1-d166dd743eea', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7685-8f4a-955a644fa130', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-713c-be93-4f5ff375fa67', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7685-8f4a-955a644fa130', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-77b5-a30a-e66ad06a4f9a', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Issue', 2, 'pending_verification', 'issue.verify_close', 'verified_closed', 'contract:transition:Issue:pending_verification:issue.verify_close:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.issue.verify_close.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.issue.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-75e3-a6dd-e25a95fd75f1', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b5-a30a-e66ad06a4f9a', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7cf5-8e25-c2d1e3c0e708', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b5-a30a-e66ad06a4f9a', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7c9f-a4c1-91fec15e78b3', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-77b5-a30a-e66ad06a4f9a', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-701a-95fc-0138f15e7f59', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Action', 2, 'pending', 'action.start', 'in_progress', 'contract:transition:Action:pending:action.start:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.action.start.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.action.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-70e2-a767-44ea143c916d', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-701a-95fc-0138f15e7f59', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7205-949e-89971d0a6b7d', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-701a-95fc-0138f15e7f59', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-791f-9edf-9d9fc69835a2', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Action', 2, 'in_progress', 'action.submit_review', 'in_review', 'contract:transition:Action:in_progress:action.submit_review:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.action.submit_review.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.action.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-79ca-9430-3ea2fe2edc7a', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-791f-9edf-9d9fc69835a2', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7b5c-84b2-35f5a6355a53', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-791f-9edf-9d9fc69835a2', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7084-8234-d443efa65c6e', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Action', 2, 'in_review', 'action.complete', 'completed', 'contract:transition:Action:in_review:action.complete:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.action.complete.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.action.transition' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-7148-82e9-6a1050fe39f5', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7084-8234-d443efa65c6e', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-725c-b7b3-18d8759df152', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7084-8234-d443efa65c6e', 'owned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-79c2-bcf4-033079db9af1', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7084-8234-d443efa65c6e', 'remediation.action.completed.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7e98-af36-01cda35170ba', '2026-09-21T00:00:00.000Z', NULL, NULL, 'Action', 2, 'completed', 'action.verify', 'verified', 'contract:transition:Action:completed:action.verify:v2', p.permission_id, 'contract:default-deny-sod:v1', 'audit.remediation.action.verify.v1', 'NONE_CONTRACTUALLY_REQUIRED', 'NONE_CONTRACTUALLY_REQUIRED', 'IDEMPOTENCY_KEY_REQUIRED', 'ROW_VERSION_COMPARE_AND_SWAP', false, 'published', '2026-09-21T00:00:00.000Z' FROM iam.permissions p WHERE p.permission_code = 'remediation.action.verify' ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-769d-9a21-23beb7e88d55', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e98-af36-01cda35170ba', 'tenant') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_scopes (lifecycle_transition_scope_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, scope_kind) VALUES ('01a0c143-2c00-75d5-b30f-2086b64bf680', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e98-af36-01cda35170ba', 'assigned_object') ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_side_effects (lifecycle_transition_side_effect_id, created_at, created_by_user_identity_id, created_by_service_principal_id, lifecycle_transition_definition_id, event_code, ordinal, is_required) VALUES ('01a0c143-2c00-74c2-a626-9bdfe18cb5d1', '2026-09-21T00:00:00.000Z', NULL, NULL, '01a0c143-2c00-7e98-af36-01cda35170ba', 'remediation.action.verified.v1', 1, true) ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-77cb-828f-d634c78b2af2', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:draft:evidence.submit:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'draft' AND command_code = 'evidence.submit' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7f29-ad4e-0470939426be', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:submitted:evidence.start_review:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'submitted' AND command_code = 'evidence.start_review' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-710a-8b80-a117a5523896', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:under_review:evidence.approve:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'under_review' AND command_code = 'evidence.approve' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7748-bdb5-00eed8db34a5', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:under_review:evidence.reject:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'under_review' AND command_code = 'evidence.reject' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7b04-a73b-64fe6c75d706', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:approved:evidence.expire:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'approved' AND command_code = 'evidence.expire' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7b13-a10e-207a4e94ecc6', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:approved:evidence.supersede:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'approved' AND command_code = 'evidence.supersede' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-71c0-b9df-9a8309f575fd', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:Evidence:rejected:evidence.revise:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'Evidence' AND from_state = 'rejected' AND command_code = 'evidence.revise' AND version_number = 1 ON CONFLICT DO NOTHING;
INSERT INTO ops_audit.lifecycle_transition_definitions (lifecycle_transition_definition_id, created_at, created_by_user_identity_id, created_by_service_principal_id, entity_type, version_number, from_state, command_code, to_state, precondition_policy_ref, permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, lifecycle_state, published_at) SELECT '01a0c143-2c00-7610-a44b-c5ac8cc7fe3e', '2026-09-21T00:00:00.000Z', NULL, NULL, entity_type, 2, from_state, command_code, to_state, 'contract:transition:AssuranceTest:in_progress:assurance_test.complete:v2:superseded', permission_id, sod_policy_ref, audit_event_code, notification_policy_ref, recalculation_policy_ref, idempotency_semantics, concurrency_semantics, system_actor_allowed, 'superseded', NULL FROM ops_audit.lifecycle_transition_definitions WHERE entity_type = 'AssuranceTest' AND from_state = 'in_progress' AND command_code = 'assurance_test.complete' AND version_number = 1 ON CONFLICT DO NOTHING;

DO $$
DECLARE physical_rows integer;
BEGIN
  SELECT count(*) INTO physical_rows FROM pg_catalog.pg_tables WHERE schemaname IN ('platform', 'iam', 'org', 'regulatory', 'controls', 'evidence', 'remediation', 'risk', 'audit', 'operations', 'third_party', 'resilience', 'privacy', 'survey', 'data', 'config', 'rules', 'integration', 'reporting', 'knowledge', 'ai', 'notification', 'ops_audit') AND NOT (schemaname = 'platform' AND tablename = 'schema_migrations');
  IF physical_rows <> 229 THEN RAISE EXCEPTION 'PRE_F5C_POSTCONDITION_EXPECTED_229_TABLES'; END IF;
  IF (SELECT count(*) FROM iam.permissions WHERE permission_code IN ('compliance.soa.create','controls.assurance_test.create')) <> 2 THEN RAISE EXCEPTION 'PRE_F5C_POSTCONDITION_PERMISSIONS'; END IF;
  IF (SELECT count(*) FROM ops_audit.lifecycle_transition_definitions WHERE created_at = '2026-09-21T00:00:00.000Z'::timestamptz) <> 39 THEN RAISE EXCEPTION 'PRE_F5C_POSTCONDITION_LIFECYCLE_DELTA'; END IF;
END $$;
