import pg from '/Users/andresbarouh/repos/tcdx-grc/node_modules/pg/lib/index.js';
import crypto from 'node:crypto';
let input='';for await(const part of process.stdin)input+=part;
const config=JSON.parse(input);
if(config.sslMode!=='require')throw Error('TLS_CONTRACT_BLOCKED');
const kc=new pg.Client({...config,ssl:{rejectUnauthorized:false},connectionTimeoutMillis:6000,query_timeout:12000});
const grc=new pg.Client({host:process.env.DATABASE_HOST,port:Number(process.env.DATABASE_PORT),database:process.env.DATABASE_NAME,user:process.env.DATABASE_USER,password:process.env.DATABASE_PASSWORD,ssl:process.env.DATABASE_SSL_MODE==='disable'?false:{rejectUnauthorized:process.env.DATABASE_SSL_MODE!=='no-verify'},connectionTimeoutMillis:6000,query_timeout:15000});
try {
 await kc.connect();await grc.connect();
 await kc.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');await grc.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');
 const kq=async(s,a=[]) => (await kc.query(s,a)).rows;const gq=async(s,a=[]) => (await grc.query(s,a)).rows;
 const users=await kq("SELECT u.id,u.enabled FROM user_entity u JOIN realm r ON r.id=u.realm_id WHERE r.name=$1 AND u.username=$2 AND u.service_account_client_link IS NULL",['tcdx-managed-identity','andres.grc']);
 if(users.length!==1)throw Error('IDENTITY_MATCH_FAILED');const u=users[0];
 const issuer='https://iam.grc.tecdex.net/realms/tcdx-managed-identity';
 const identityKey='oidc:'+crypto.createHash('sha256').update(issuer+'\0'+u.id).digest('base64url');
 const ids=await gq('SELECT user_identity_id,lifecycle_state,last_authenticated_at FROM iam.user_identities WHERE identity_key=$1',[identityKey]);
 if(ids.length!==1)throw Error('CANONICAL_MAPPING_FAILED');const id=ids[0].user_identity_id;
 const assignments=await gq("SELECT count(*)::int AS total,count(*) FILTER(WHERE r.role_code='PLATFORM_ADMIN' AND r.is_baseline AND r.ownership_class='PLATFORM_CONTROL' AND r.tenant_id IS NULL AND r.lifecycle_state='published' AND pa.ownership_class='PLATFORM_CONTROL' AND pa.valid_from<=transaction_timestamp() AND (pa.valid_to IS NULL OR pa.valid_to>transaction_timestamp()))::int AS active_admin FROM iam.platform_role_assignments pa JOIN iam.roles r USING(role_id) WHERE pa.user_identity_id=$1",[id]);
 const membership=(await gq('SELECT count(*)::int AS n FROM iam.tenant_memberships WHERE user_identity_id=$1',[id]))[0].n;
 const tenantRoles=(await gq('SELECT count(*)::int AS n FROM iam.membership_roles mr JOIN iam.tenant_memberships tm USING(tenant_membership_id) WHERE tm.user_identity_id=$1 AND mr.valid_from<=transaction_timestamp() AND (mr.valid_to IS NULL OR mr.valid_to>transaction_timestamp())',[id]))[0].n;
 const actions=(await kq('SELECT required_action FROM user_required_action WHERE user_id=$1 ORDER BY 1',[u.id])).map(x=>x.required_action);
 const otp=(await kq("SELECT count(*)::int AS n FROM credential WHERE user_id=$1 AND type='otp'",[u.id]))[0].n;
 const login=(await kq("SELECT count(*)::int AS n FROM event_entity WHERE user_id=$1 AND type IN ('LOGIN','CODE_TO_TOKEN','UPDATE_PASSWORD','UPDATE_TOTP','LOGIN_ERROR')",[u.id]))[0].n;
 const sessions=(await kq('SELECT count(*)::int AS n FROM offline_user_session WHERE user_id=$1',[u.id]))[0].n;
 const realms=await kq("SELECT name,enabled,login_theme,events_enabled,admin_events_enabled,admin_events_details_enabled FROM realm WHERE name IN ('master','tcdx-managed-identity') ORDER BY name");const managed=realms.find(r=>r.name==='tcdx-managed-identity'),master=realms.find(r=>r.name==='master');if(!managed?.enabled||managed.login_theme!=='tcdx-grc'||!master?.events_enabled||!master.admin_events_enabled||master.admin_events_details_enabled!==false)throw Error('IAM_REALM_SETTINGS_DRIFT');


 const testUsers=await kq('SELECT u.id,u.username,u.first_name,u.last_name,u.enabled FROM user_entity u JOIN realm r ON r.id=u.realm_id WHERE r.name=$1 AND u.username=$2 AND u.service_account_client_link IS NULL',['tcdx-managed-identity','admin.acme']);
 if(testUsers.length!==1)throw Error('HUMAN_TEST_USER_MATCH_FAILED');const tu=testUsers[0];
 const testKey='oidc:'+crypto.createHash('sha256').update(issuer+'\0'+tu.id).digest('base64url');
 const testIds=await gq('SELECT user_identity_id,display_name,lifecycle_state FROM iam.user_identities WHERE identity_key=$1',[testKey]);
 if(testIds.length!==1)throw Error('HUMAN_TEST_CANONICAL_MAPPING_FAILED');const tid=testIds[0].user_identity_id;
 const memberships=await gq(`SELECT m.tenant_membership_id,m.tenant_id,m.user_identity_id,m.membership_state,m.joined_at,m.ended_at,t.display_name AS tenant_name,t.tenant_code,t.lifecycle_state AS tenant_state FROM iam.tenant_memberships m JOIN platform.tenants t USING(tenant_id) WHERE m.user_identity_id=$1 ORDER BY m.tenant_membership_id`,[tid]);
 const roleAssignments=await gq(`SELECT mr.membership_role_id,mr.tenant_membership_id,mr.tenant_id,mr.role_id,mr.valid_from,mr.valid_to,mr.scope_kind,r.role_code,r.name AS role_name,r.ownership_class,r.lifecycle_state,r.tenant_id AS role_tenant FROM iam.membership_roles mr JOIN iam.tenant_memberships m USING(tenant_membership_id) JOIN iam.roles r USING(role_id) WHERE m.user_identity_id=$1 ORDER BY mr.membership_role_id`,[tid]);
 const testPlatform=(await gq('SELECT count(*)::int AS n FROM iam.platform_role_assignments WHERE user_identity_id=$1',[tid]))[0].n;
 const audit=await gq(`SELECT audit_event_id,event_code,command_code,aggregate_type,aggregate_id,actor_user_identity_id,tenant_id,ownership_class,correlation_id,occurred_at,outcome,after_payload->>'tenant_id' AS target_tenant,after_payload->>'user_identity_id' AS target_identity FROM ops_audit.audit_events WHERE (aggregate_id=$1::uuid OR aggregate_id IN(SELECT tenant_membership_id FROM iam.tenant_memberships WHERE user_identity_id=$1) OR aggregate_id IN(SELECT membership_role_id FROM iam.membership_roles mr JOIN iam.tenant_memberships m USING(tenant_membership_id) WHERE m.user_identity_id=$1) OR after_payload->>'user_identity_id'=$1::text) AND command_code IN('managedIdentityProvision','tenantUserOnboardingCreate','tenantInitialOnboardingCreate') ORDER BY occurred_at,audit_event_id`,[tid]);
 const auditSecretFields=(await gq(`SELECT count(*)::int AS n FROM ops_audit.audit_events a WHERE a.audit_event_id=ANY($1::uuid[]) AND (EXISTS(SELECT 1 FROM jsonb_object_keys(CASE WHEN jsonb_typeof(a.before_payload)='object' THEN a.before_payload ELSE '{}'::jsonb END) k WHERE k~* 'password|credential|secret|token|seed|verifier') OR EXISTS(SELECT 1 FROM jsonb_object_keys(CASE WHEN jsonb_typeof(a.after_payload)='object' THEN a.after_payload ELSE '{}'::jsonb END) k WHERE k~* 'password|credential|secret|token|seed|verifier'))`,[audit.map(a=>a.audit_event_id)]))[0].n;
 const keycloakAudit=await kq(`SELECT a.id,a.operation_type,a.resource_type,a.resource_path,to_timestamp(a.admin_event_time/1000.0) AS occurred_at,a.error,a.representation IS NULL AS representation_absent FROM admin_event_entity a JOIN realm r ON r.id=a.realm_id WHERE r.name=$1 AND (a.resource_path=$2 OR a.resource_path LIKE $3) ORDER BY a.admin_event_time`,['tcdx-managed-identity','users/'+tu.id,'users/'+tu.id+'/%']);
 const client=await kq(`SELECT c.id,c.client_id,c.enabled,c.public_client,c.bearer_only,c.protocol,c.service_accounts_enabled,c.client_authenticator_type,c.standard_flow_enabled,c.implicit_flow_enabled,c.direct_access_grants_enabled FROM client c JOIN realm r ON r.id=c.realm_id WHERE r.name=$1 AND c.client_id=$2`,['tcdx-managed-identity','tcdx-grc']);
 if(client.length!==1)throw Error('OIDC_CLIENT_MATCH_FAILED');const cid=client[0].id;
 const clientAttrs=await kq("SELECT name,value FROM client_attributes WHERE client_id=$1 AND name IN ('pkce.code.challenge.method','post.logout.redirect.uris') ORDER BY name",[cid]);
 const redirects=await kq('SELECT value FROM redirect_uris WHERE client_id=$1 ORDER BY value',[cid]);
 const flow=await kq(`SELECT f.id,f.alias FROM realm r JOIN authentication_flow f ON f.id=r.browser_flow WHERE r.name=$1`,['tcdx-managed-identity']);

 const executions=await kq(`WITH RECURSIVE tree AS(SELECT f.id,0 AS depth FROM authentication_flow f WHERE f.id=$1 UNION ALL SELECT e.auth_flow_id,t.depth+1 FROM tree t JOIN authentication_execution e ON e.flow_id=t.id WHERE e.authenticator_flow AND e.requirement<>3 AND t.depth<8) SELECT f.alias AS flow_alias,t.depth,e.authenticator,e.requirement,e.priority,e.authenticator_flow FROM tree t JOIN authentication_flow f ON f.id=t.id JOIN authentication_execution e ON e.flow_id=t.id ORDER BY t.depth,f.alias,e.priority`,[flow[0]?.id]);
 const authConfig=await kq(`WITH RECURSIVE tree AS(SELECT f.id,0 AS depth FROM authentication_flow f WHERE f.id=$1 UNION ALL SELECT e.auth_flow_id,t.depth+1 FROM tree t JOIN authentication_execution e ON e.flow_id=t.id WHERE e.authenticator_flow AND e.requirement<>3 AND t.depth<8) SELECT e.authenticator,c.name,c.value FROM tree t JOIN authentication_execution e ON e.flow_id=t.id JOIN authenticator_config_entry c ON c.authenticator_id=e.auth_config ORDER BY t.depth,e.priority,c.name`,[flow[0]?.id]);
 const mapper=await kq(`SELECT p.name,p.protocol_mapper_name FROM protocol_mapper p WHERE p.client_id=$1 OR p.client_scope_id IN(SELECT scope_id FROM client_scope_client WHERE client_id=$1)`,[cid]);
 const grcRoleCodes=(await gq('SELECT DISTINCT role_code FROM iam.roles')).map(r=>r.role_code);
 const forbiddenRoles=await kq(`SELECT k.name FROM keycloak_role k WHERE (k.realm_id=(SELECT id FROM realm WHERE name=$1) OR k.client IN(SELECT id FROM client WHERE realm_id=(SELECT id FROM realm WHERE name=$1))) AND (upper(k.name)=ANY($2::text[]) OR k.name LIKE 'platform.%')`,['tcdx-managed-identity',grcRoleCodes]);
 const userRoles=await kq(`SELECT k.name,k.client_role FROM user_role_mapping m JOIN keycloak_role k ON k.id=m.role_id WHERE m.user_id=$1 ORDER BY k.name`,[u.id]);

 const mapperConfig=await kq(`SELECT pc.name,pc.value FROM protocol_mapper p JOIN protocol_mapper_config pc ON pc.protocol_mapper_id=p.id WHERE (p.client_id=$1 OR p.client_scope_id IN(SELECT scope_id FROM client_scope_client WHERE client_id=$1)) AND p.protocol_mapper_name='oidc-amr-mapper' AND pc.name IN('id.token.claim','access.token.claim','userinfo.token.claim','introspection.token.claim') ORDER BY pc.name`,[cid]);
 const amrScope=await kq(`SELECT sc.name,csc.default_scope FROM protocol_mapper p JOIN client_scope sc ON sc.id=p.client_scope_id JOIN client_scope_client csc ON csc.scope_id=sc.id WHERE csc.client_id=$1 AND p.protocol_mapper_name='oidc-amr-mapper'`,[cid]);
 const webOrigins=await kq('SELECT value FROM web_origins WHERE client_id=$1 ORDER BY value',[cid]);
 const actorGrants=await gq(`SELECT count(*)::int AS n FROM iam.platform_role_assignments pa JOIN iam.roles r USING(role_id) JOIN iam.role_permissions rp USING(role_id) JOIN iam.permissions p USING(permission_id) WHERE pa.user_identity_id=$1 AND pa.valid_from<=transaction_timestamp() AND (pa.valid_to IS NULL OR pa.valid_to>transaction_timestamp()) AND r.role_code='PLATFORM_ADMIN' AND r.ownership_class='PLATFORM_CONTROL' AND r.tenant_id IS NULL AND r.lifecycle_state='published' AND rp.ownership_class='PLATFORM_CONTROL' AND rp.tenant_id IS NULL AND p.permission_code='platform.tenant_user.onboard' AND p.lifecycle_state='published'`,[id]);
 const acmeRow=await gq("SELECT tenant_id,md5((to_jsonb(t))::text) AS nonsecret_row_fingerprint FROM platform.tenants t WHERE tenant_code='ACME-1'");
 const originalTenantFingerprint=await gq("SELECT count(*)::int AS rows,md5(coalesce(string_agg(md5(to_jsonb(t)::text),'' ORDER BY md5(to_jsonb(t)::text)),'')) AS nonsecret_fingerprint FROM platform.tenants t WHERE tenant_id<>$1::uuid",[memberships.find(m=>m.tenant_code==='ACME 2')?.tenant_id]);
 const attributes=await kq("SELECT count(*)::int AS n FROM user_attribute WHERE user_id=ANY($1::text[]) AND name ~* 'tenant|membership|platform_role|grc_role'",[[u.id,tu.id]]);

 const acme2=memberships.find(m=>m.tenant_code==='ACME 2');
 const humanActor=audit.find(a=>a.event_code==='audit.platform.tenant_user.onboard.v1')?.actor_user_identity_id;
 const actorNoNewTenantAuthority=await gq(`SELECT count(*)::int AS n FROM iam.tenant_memberships WHERE user_identity_id=$1 AND tenant_id=$2`,[humanActor,acme2?.tenant_id]);
 const allHumanTestAudit=(await gq(`SELECT count(*)::int AS n FROM ops_audit.audit_events WHERE actor_user_identity_id=$1 AND occurred_at>=$2::timestamptz AND aggregate_id IN($3::uuid,$4::uuid,$5::uuid)`,[humanActor,'2026-10-07T19:20:00Z',tid,memberships[0].tenant_membership_id,acme2?.tenant_id]))[0].n;

 const humanEvents=await kq(`SELECT e.id,e.type,to_timestamp(e.event_time/1000.0) AS occurred_at,e.error,e.client_id,CASE WHEN e.details_json IS NULL THEN NULL ELSE e.details_json::jsonb->>'auth_method' END AS auth_method,CASE WHEN e.details_json IS NULL THEN NULL ELSE e.details_json::jsonb->>'response_type' END AS response_type,CASE WHEN e.details_json IS NULL THEN NULL ELSE e.details_json::jsonb->>'redirect_uri' END AS redirect_uri,CASE WHEN e.details_json IS NULL THEN NULL ELSE e.details_json::jsonb->>'grant_type' END AS grant_type FROM event_entity e WHERE e.user_id=$1 ORDER BY e.event_time,e.id`,[u.id]);
 const metadataColumns=await kq("SELECT table_name,column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name IN('offline_user_session','offline_client_session','user_session') ORDER BY 1,ordinal_position");
 const deniedAudits=await gq("SELECT audit_event_id,event_code,command_code,occurred_at,outcome,correlation_id FROM ops_audit.audit_events WHERE actor_user_identity_id=$1 AND occurred_at>='2026-10-07T20:58:00Z' ORDER BY occurred_at",[id]);

 const userSessionMetadata=await kq(`SELECT created_on,last_session_refresh,offline_flag,CASE WHEN jsonb_typeof(data::jsonb)='object' THEN ARRAY(SELECT jsonb_object_keys(data::jsonb)) ELSE NULL END AS safe_top_level_keys,CASE WHEN jsonb_typeof(data::jsonb->'notes')='object' THEN ARRAY(SELECT jsonb_object_keys(data::jsonb->'notes')) ELSE NULL END AS safe_note_keys FROM offline_user_session WHERE user_id=$1`,[u.id]);
 const clientSessionMetadata=await kq(`SELECT cs.offline_flag,cs.timestamp,CASE WHEN jsonb_typeof(cs.data::jsonb)='object' THEN ARRAY(SELECT jsonb_object_keys(cs.data::jsonb)) ELSE NULL END AS safe_top_level_keys,CASE WHEN jsonb_typeof(cs.data::jsonb->'notes')='object' THEN ARRAY(SELECT jsonb_object_keys(cs.data::jsonb->'notes')) ELSE NULL END AS safe_note_keys FROM offline_client_session cs JOIN offline_user_session us ON us.user_session_id=cs.user_session_id WHERE us.user_id=$1`,[u.id]);

 const factorExecution=await kq(`SELECT data::jsonb #>> '{notes,authenticators-completed}' AS completed_factor_references,data::jsonb #>> '{notes,AUTH_TIME}' AS authentication_time FROM offline_user_session WHERE user_id=$1`,[u.id]);
 const safeClientNotes=await kq(`SELECT cs.data::jsonb #>> '{notes,iss}' AS issuer,cs.data::jsonb #>> '{notes,clientId}' AS client_id,cs.data::jsonb #>> '{notes,redirect_uri}' AS redirect_uri,cs.data::jsonb #>> '{notes,code_challenge_method}' AS challenge_method,cs.data::jsonb #>> '{notes,response_type}' AS response_type,(cs.data::jsonb #>> '{notes,nonce}') IS NOT NULL AS nonce_present,(cs.data::jsonb #>> '{notes,state}') IS NOT NULL AS state_present,(cs.data::jsonb #>> '{notes,code_challenge}') IS NOT NULL AS challenge_present FROM offline_client_session cs JOIN offline_user_session us USING(user_session_id) WHERE us.user_id=$1`,[u.id]);
 const authTimeMapper=await kq(`SELECT p.name,p.protocol_mapper_name,pc.name AS config_name,pc.value FROM protocol_mapper p JOIN protocol_mapper_config pc ON pc.protocol_mapper_id=p.id WHERE (p.client_id=$1 OR p.client_scope_id IN(SELECT scope_id FROM client_scope_client WHERE client_id=$1)) AND p.name='auth_time' ORDER BY pc.name`,[cid]);
 const scopeLinks=await kq(`SELECT sc.name,csc.default_scope FROM client_scope_client csc JOIN client_scope sc ON sc.id=csc.scope_id WHERE csc.client_id=$1 ORDER BY sc.name`,[cid]);

 const executionReferenceCheck=await kq(`SELECT e.authenticator,c.value AS amr_reference,(us.data::jsonb->'notes'->>'authenticators-completed')::jsonb ? e.id AS verified_execution_present FROM offline_user_session us CROSS JOIN authentication_execution e JOIN authenticator_config_entry c ON c.authenticator_id=e.auth_config WHERE us.user_id=$1 AND e.realm_id=us.realm_id AND c.name='default.reference.value' ORDER BY e.authenticator`,[u.id]);
 const clientAttributesPublic=await kq("SELECT name,value FROM client_attributes WHERE client_id=$1 AND name IN('exclude.session.state.from.auth.response','use.refresh.tokens','client.session.idle.timeout','client.session.max.lifespan','access.token.lifespan','id.token.signed.response.alg','client.use.lightweight.access.token.enabled') ORDER BY name",[cid]);
 const technicalRoles=await kq(`SELECT u.username,k.name FROM user_entity u JOIN realm r ON r.id=u.realm_id LEFT JOIN user_role_mapping m ON m.user_id=u.id LEFT JOIN keycloak_role k ON k.id=m.role_id WHERE r.name IN ('master','tcdx-managed-identity') AND (u.service_account_client_link IS NOT NULL OR u.username IN('andres.barouh','tcdx-iam-bootstrap','tcdx-iam-recovery')) ORDER BY u.username,k.name`);
 const configurationAudit=await kq(`SELECT a.id,a.operation_type,a.resource_type,a.resource_path,to_timestamp(a.admin_event_time/1000.0) AS occurred_at,a.error,a.representation IS NULL AS representation_absent FROM admin_event_entity a JOIN realm r ON r.id=a.realm_id WHERE r.name=$1 AND a.admin_event_time>=$2 AND a.operation_type='UPDATE' ORDER BY a.admin_event_time`,['tcdx-managed-identity',Date.parse('2026-10-07T21:09:00Z')]);
 const technicalPrincipalState=await kq(`SELECT u.username,u.enabled,u.service_account_client_link IS NOT NULL AS machine_principal FROM user_entity u JOIN realm r ON r.id=u.realm_id WHERE r.name IN ('master','tcdx-managed-identity') AND (u.service_account_client_link IS NOT NULL OR u.username IN ('andres.barouh','tcdx-iam-bootstrap','tcdx-iam-recovery')) ORDER BY u.username`);
 const ceremony={configurationAudit,technicalPrincipalState,technicalRoles,executionReferenceCheck,clientAttributesPublic,factorExecution,safeClientNotes,authTimeMapper,scopeLinks,userSessionMetadata,clientSessionMetadata,humanEvents,metadataColumns,deniedAudits,currentActions:actions,otp,enabled:u.enabled,lastAuthenticated:ids[0].last_authenticated_at};

 const identityAudits=await gq(`SELECT audit_event_id,event_code,command_code,aggregate_type,aggregate_id,actor_user_identity_id,tenant_id,ownership_class,correlation_id,occurred_at,outcome,after_payload->>'reason' AS reason FROM ops_audit.audit_events WHERE aggregate_id=$1::uuid OR actor_user_identity_id=$1::uuid OR after_payload->>'user_identity_id'=$1::text OR aggregate_id IN (SELECT platform_role_assignment_id FROM iam.platform_role_assignments WHERE user_identity_id=$1) ORDER BY occurred_at`,[id]);
 const revokes=identityAudits.filter(a=>a.event_code==='audit.platform.managed_identity.session_revoke.v1');
 const latestRevoke=revokes.at(-1);
 const revokedGenerationSessions=latestRevoke?(await kq('SELECT count(*)::int AS n FROM offline_user_session WHERE user_id=$1 AND created_on<= $2',[u.id,Math.floor(Date.parse(latestRevoke.occurred_at)/1000)]))[0].n:null;
 const currentSessionGenerations=await kq('SELECT offline_flag,count(*)::int AS count,min(created_on) AS first_created_epoch,max(created_on) AS last_created_epoch FROM offline_user_session WHERE user_id=$1 GROUP BY offline_flag',[u.id]);
 const revokeIdempotency=await gq(`SELECT idempotency_record_id,ownership_class,tenant_id,actor_user_identity_id,operation_code,result_status_code,result_ref,created_at,first_seen_at,expires_at,request_hash IS NOT NULL AS request_hash_present,response_hash IS NOT NULL AS response_hash_present FROM ops_audit.idempotency_records WHERE operation_code='managedIdentitySessionRevoke' AND actor_user_identity_id=$1 ORDER BY created_at`,['01a0cfae-d860-730d-88b8-d8b1b3f5d7dc']);
 const effectivePlatformPermissions=await gq(`SELECT DISTINCT p.permission_code FROM iam.platform_role_assignments pa JOIN iam.roles r USING(role_id) JOIN iam.role_permissions rp USING(role_id) JOIN iam.permissions p USING(permission_id) WHERE pa.user_identity_id=$1 AND pa.ownership_class='PLATFORM_CONTROL' AND pa.valid_from<=transaction_timestamp() AND (pa.valid_to IS NULL OR pa.valid_to>transaction_timestamp()) AND r.ownership_class='PLATFORM_CONTROL' AND r.tenant_id IS NULL AND r.lifecycle_state='published' AND rp.ownership_class='PLATFORM_CONTROL' AND rp.tenant_id IS NULL AND p.lifecycle_state='published' ORDER BY p.permission_code`,[id]);
 const lifecycleAudit=await gq(`SELECT event_code,command_code,outcome,count(*)::int AS events,count(DISTINCT actor_user_identity_id)::int AS real_actor_count,min(occurred_at) AS first_at,max(occurred_at) AS last_at FROM ops_audit.audit_events WHERE command_code ~* 'applicability|assessment|soa|assurance|evidence|upload|retention|issue|action' GROUP BY event_code,command_code,outcome ORDER BY command_code,event_code`);
 const auditSecretKeyScan=await gq(`WITH RECURSIVE nodes(value) AS (SELECT coalesce(before_payload,'{}'::jsonb) FROM ops_audit.audit_events UNION ALL SELECT coalesce(after_payload,'{}'::jsonb) FROM ops_audit.audit_events UNION ALL SELECT e.value FROM nodes n CROSS JOIN LATERAL (SELECT value FROM jsonb_each(CASE WHEN jsonb_typeof(n.value)='object' THEN n.value ELSE '{}'::jsonb END) UNION ALL SELECT value FROM jsonb_array_elements(CASE WHEN jsonb_typeof(n.value)='array' THEN n.value ELSE '[]'::jsonb END)) e) SELECT count(*)::int AS forbidden_secret_keys FROM nodes n CROSS JOIN LATERAL jsonb_object_keys(CASE WHEN jsonb_typeof(n.value)='object' THEN n.value ELSE '{}'::jsonb END) k WHERE k~* '^(password|otp|totp_secret|totp_seed|qr|token|cookie|client_secret|access_token|refresh_token|id_token|private_key|temporary_credential)$'`);
 const platformAssignmentsCurrent=await gq(`SELECT pa.platform_role_assignment_id,pa.user_identity_id,pa.role_id,r.role_code,pa.valid_from,pa.valid_to,pa.valid_from<=transaction_timestamp() AND (pa.valid_to IS NULL OR pa.valid_to>transaction_timestamp()) AS active FROM iam.platform_role_assignments pa JOIN iam.roles r USING(role_id) WHERE pa.user_identity_id=$1 ORDER BY pa.valid_from`,[id]);
 const existingActivePlatformAdmins=await gq(`SELECT pa.user_identity_id,u.display_name,r.role_code FROM iam.platform_role_assignments pa JOIN iam.roles r USING(role_id) JOIN iam.user_identities u USING(user_identity_id) WHERE u.lifecycle_state='active' AND r.role_code='PLATFORM_ADMIN' AND r.ownership_class='PLATFORM_CONTROL' AND pa.valid_from<=transaction_timestamp() AND (pa.valid_to IS NULL OR pa.valid_to>transaction_timestamp()) ORDER BY pa.user_identity_id`);
 const adapterServiceAccountRoleExpansion=await kq(`WITH RECURSIVE roles(id) AS (SELECT urm.role_id::text FROM user_role_mapping urm JOIN user_entity u ON u.id=urm.user_id WHERE u.service_account_client_link IN(SELECT c.id FROM client c JOIN realm r ON r.id=c.realm_id WHERE r.name='tcdx-managed-identity' AND c.client_id='tcdx-grc-managed-identity-provisioner') UNION SELECT cr.child_role::text FROM roles rr JOIN composite_role cr ON cr.composite=rr.id) SELECT k.name FROM roles rr JOIN keycloak_role k ON k.id=rr.id ORDER BY k.name`);

 const kcTargetAdminAudit=await kq(`SELECT a.id,a.operation_type,a.resource_type,to_timestamp(a.admin_event_time/1000.0) AS occurred_at,a.error,a.representation IS NULL AS representation_absent,CASE WHEN a.resource_path=$2 THEN 'TARGET_USER' WHEN a.resource_path=$3 THEN 'TARGET_LOGOUT' WHEN a.resource_path LIKE $4 THEN 'TARGET_USER_SUBRESOURCE' ELSE 'OTHER' END AS target_kind FROM admin_event_entity a JOIN realm r ON r.id=a.realm_id WHERE r.name=$1 AND (a.resource_path=$2 OR a.resource_path LIKE $4) ORDER BY a.admin_event_time`,['tcdx-managed-identity','users/'+u.id,'users/'+u.id+'/logout','users/'+u.id+'/%']);
 const auditCoverage={revokedGenerationSessions,currentSessionGenerations,auditSecretKeyScan,platformAssignmentsCurrent,existingActivePlatformAdmins,adapterServiceAccountRoleExpansion,identityAudits,revokes,revokeIdempotency,effectivePlatformPermissions,lifecycleAudit,kcTargetAdminAudit};
 ceremony.auditCoverage=auditCoverage;
 const extra={ceremony,humanTest:{username:tu.username,displayName:testIds[0].display_name,keycloakExactlyOne:true,identityExactlyOne:true,issuerSubjectMappingExact:true,identityActive:testIds[0].lifecycle_state==='active',enabled:tu.enabled,canonicalIdentityId:tid,memberships,roleAssignments,actorNoNewTenantAuthority,allHumanTestAudit,acmeRow,originalTenantFingerprint,platformAssignments:testPlatform,audit,auditSecretFields,keycloakAudit},iam:{mapperConfig,amrScope,webOrigins,actorGrants,attributes,client,clientAttrs,redirects,flow,executions,authConfig,mapper,forbiddenRoles,userRoles}};

 const membershipDetails=await gq(`SELECT m.tenant_membership_id,m.tenant_id,t.tenant_code,m.membership_state,m.joined_at,m.ended_at,m.created_at,m.created_by_user_identity_id FROM iam.tenant_memberships m JOIN platform.tenants t USING(tenant_id) WHERE m.user_identity_id=$1`,[id]);
 const membershipOriginAudits=await gq(`SELECT audit_event_id,event_code,command_code,aggregate_id,actor_user_identity_id,tenant_id,correlation_id,occurred_at,outcome,after_payload->>'reason' AS reason FROM ops_audit.audit_events WHERE aggregate_id IN(SELECT tenant_membership_id FROM iam.tenant_memberships WHERE user_identity_id=$1) OR (after_payload->>'user_identity_id'=$1::text AND command_code IN('tenantUserOnboardingCreate','membershipInvitationCreate','membershipInvitationAccept')) ORDER BY occurred_at`,[id]);
  const result={membershipDetails,membershipOriginAudits,extra,keycloakExactlyOne:true,grcIdentityExactlyOne:true,issuerSubjectMappingExact:true,realmSettings:realms,capturedAt:new Date().toISOString(),exists:true,enabled:u.enabled,identityActive:ids[0].lifecycle_state==='active',platformAssignments:assignments[0].total,activePlatformAdmin:assignments[0].active_admin,membership,tenantRoles,requiredActions:actions,otp,firstLoginRelatedEvents:login,lastAuthenticatedNull:ids[0].last_authenticated_at===null,sessions,readOnly:true,credentialContentsSelected:false,credentialHashesCaptured:false};
 result.preActivationPredicateMatched=result.exists&&result.enabled&&result.identityActive&&result.platformAssignments===1&&result.activePlatformAdmin===1&&membership===0&&tenantRoles===0&&actions.includes('UPDATE_PASSWORD')&&actions.includes('CONFIGURE_TOTP')&&otp===0&&login===0&&result.lastAuthenticatedNull&&sessions===0;
 result.pass=result.exists&&result.enabled&&result.identityActive&&result.activePlatformAdmin===1&&membership===1&&tenantRoles===0;

 await kc.query('ROLLBACK');await grc.query('ROLLBACK');console.log(JSON.stringify(result));
 if(!result.pass)process.exitCode=1;
}catch(e){console.log(JSON.stringify({pass:false,safeErrorClass:e.code??e.constructor.name,safeErrorMessage:["42P19","42804"].includes(e.code)?e.message:undefined,...(e.code==="42703"?{safeColumnError:e.message}:{})}));process.exitCode=1;}finally{await kc.end().catch(()=>{});await grc.end().catch(()=>{});}
