import pg from '/Users/andresbarouh/repos/tcdx-grc/node_modules/pg/lib/index.js';
import fs from 'node:fs';
if(process.env.DATABASE_HOST!=='192.168.2.40'||process.env.DATABASE_NAME!=='tcdx-grc')throw Error('TARGET_BLOCKED');
const client=new pg.Client({host:process.env.DATABASE_HOST,port:Number(process.env.DATABASE_PORT),database:process.env.DATABASE_NAME,user:process.env.DATABASE_USER,password:process.env.DATABASE_PASSWORD,ssl:process.env.DATABASE_SSL_MODE==='disable'?false:{rejectUnauthorized:process.env.DATABASE_SSL_MODE!=='no-verify'},connectionTimeoutMillis:6000,query_timeout:30000});
const result={capturedAt:new Date().toISOString(),readOnly:true};
try {
 await client.connect(); await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');
 const q=async(s,a=[]) => (await client.query(s,a)).rows;
 result.tenants=await q('SELECT tenant_id,tenant_code,display_name,lifecycle_state FROM platform.tenants ORDER BY display_name');
 result.actors=await q(`SELECT u.user_identity_id,u.display_name,u.lifecycle_state,t.tenant_id,t.display_name AS tenant_name,m.tenant_membership_id,m.membership_state,array_agg(DISTINCT r.role_code) FILTER(WHERE r.role_id IS NOT NULL) AS roles FROM iam.user_identities u JOIN iam.tenant_memberships m USING(user_identity_id) JOIN platform.tenants t USING(tenant_id) LEFT JOIN iam.membership_roles mr ON mr.tenant_membership_id=m.tenant_membership_id AND mr.tenant_id=m.tenant_id AND mr.valid_from<=transaction_timestamp() AND (mr.valid_to IS NULL OR mr.valid_to>transaction_timestamp()) LEFT JOIN iam.roles r ON r.role_id=mr.role_id AND r.tenant_id=m.tenant_id AND r.lifecycle_state='published' GROUP BY 1,2,3,4,5,6,7 ORDER BY t.display_name,u.display_name`);
 result.subjects=await q('SELECT subject_id,tenant_id,subject_type,canonical_key,display_name,lifecycle_state FROM org.subjects');
 result.subscriptions=await q('SELECT tenant_id,subscription_id,plan_version_id,lifecycle_state,starts_at,ends_at FROM platform.subscriptions');
 result.entitlements=await q('SELECT s.tenant_id,c.capability_group,e.is_enabled FROM platform.subscriptions s JOIN platform.entitlements e USING(plan_version_id) JOIN platform.capabilities c USING(capability_id) WHERE s.lifecycle_state=\'active\' ORDER BY s.tenant_id,c.capability_group');
 const names=['regulatory.requirement_applicabilities','regulatory.requirement_assessments','regulatory.statements_of_applicability','controls.control_assessments','controls.assurance_tests','evidence.evidence_requests','evidence.evidences','evidence.evidence_versions','evidence.evidence_reviews','evidence.documents','evidence.document_versions','evidence.file_objects','privacy.retention_policies','remediation.issues','remediation.actions','remediation.action_verifications'];
 result.coreCounts={};for(const n of names)result.coreCounts[n]=await q(`SELECT tenant_id,count(*)::int AS count FROM ${n} GROUP BY tenant_id`);
 result.tenantControls=await q("SELECT tenant_id,control_id,control_code,name,lifecycle_state FROM controls.controls WHERE tenant_id IS NOT NULL");
 result.validationAccess=await q('SELECT regulatory_pack_validation_access_id,tenant_id,regulatory_pack_version_id,regulatory_pack_validation_provenance_id,lifecycle_state,effective_from,effective_to FROM platform.regulatory_pack_validation_accesses');
 result.requiredReference=await q("SELECT r.requirement_id,r.requirement_code,r.framework_version_id,c.control_id,cv.control_version_id,c.control_code FROM regulatory.requirements r JOIN regulatory.requirement_control_mappings m USING(requirement_id) JOIN controls.control_versions cv USING(control_version_id) JOIN controls.controls c USING(control_id) WHERE r.framework_version_id='01a0ea93-867a-7432-a041-2179e0a543f8' AND c.control_code='QUALITY-001' ORDER BY r.requirement_code LIMIT 1");
 result.coreAudits=await q("SELECT command_code,outcome,count(*)::int AS count FROM ops_audit.audit_events WHERE command_code ~ '^(applicability|requirementAssessment|soa|control|assuranceTest|evidence|issue|action|retentionPolicy|upload)' GROUP BY command_code,outcome ORDER BY command_code");
 result.retentionGrants=await q("SELECT r.role_id,r.role_code,r.tenant_id,p.permission_code FROM iam.roles r JOIN iam.role_permissions rp USING(role_id) JOIN iam.permissions p USING(permission_id) WHERE p.permission_code LIKE 'privacy.retention_policy.%' ORDER BY r.tenant_id,r.role_code,p.permission_code");
 result.methodologyTables=await q("SELECT table_schema,table_name FROM information_schema.tables WHERE table_type='BASE TABLE' AND table_schema NOT IN ('pg_catalog','information_schema') AND table_name ILIKE '%methodolog%'");
 result.configurationDefinitions=await q('SELECT configuration_definition_id,configuration_code,version_number,lifecycle_state FROM config.configuration_definitions');
 result.qaRecords={};for(const n of ['regulatory.requirement_assessments','controls.control_assessments','regulatory.requirement_applicabilities','regulatory.statements_of_applicability','controls.assurance_tests','evidence.evidence_requests','evidence.evidences','evidence.evidence_versions','privacy.retention_policies','remediation.issues','remediation.actions']){result.qaRecords[n]=await q(`SELECT to_jsonb(t)-ARRAY['identity_key'] AS record FROM ${n} t WHERE tenant_id='01a0cfc7-0c97-75a3-890f-d6ca9db8bbe9'`);}
 result.qaAudits=await q("SELECT audit_event_id,event_code,command_code,aggregate_type,aggregate_id,actor_user_identity_id,tenant_id,ownership_class,correlation_id,occurred_at,outcome,after_payload->>'lifecycle_state' AS after_state,after_payload->>'methodology_version_ref' AS methodology_version_ref FROM ops_audit.audit_events WHERE tenant_id='01a0cfc7-0c97-75a3-890f-d6ca9db8bbe9' AND occurred_at>='2026-10-07T23:00:00Z' ORDER BY occurred_at");
 result.qaSupport={};for(const n of ['evidence.evidence_reviews','evidence.evidence_links','remediation.action_verifications','remediation.action_evidence_links'])result.qaSupport[n]=await q(`SELECT to_jsonb(t) AS record FROM ${n} t WHERE tenant_id='01a0cfc7-0c97-75a3-890f-d6ca9db8bbe9'`);
 result.qaSupport['evidence.file_objects']=await q("SELECT file_object_id,tenant_id,original_filename,declared_mime,detected_mime,size_bytes,classification,retention_policy_id,scan_status,scan_completed_at FROM evidence.file_objects WHERE tenant_id='01a0cfc7-0c97-75a3-890f-d6ca9db8bbe9'");
 result.methodologyPublicationAudits=await q("SELECT audit_event_id,event_code,command_code,aggregate_type,aggregate_id,actor_user_identity_id,tenant_id,ownership_class,correlation_id,occurred_at,outcome,after_payload->>'actor_kind' AS actor_kind,after_payload->>'approval' AS human_approval FROM ops_audit.audit_events WHERE command_code='migration.20261007000200' ORDER BY event_code");
 result.methodologyCatalogs={};for(const n of ['regulatory.compliance_methodologies','controls.control_effectiveness_methodologies'])result.methodologyCatalogs[n]=await q(`SELECT to_jsonb(t) AS record FROM ${n} t`);
 await client.query('ROLLBACK');
 fs.writeFileSync('/tmp/tcdx-grc-phase5-integration-core-state.json',JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify({capturedAt:result.capturedAt,readOnly:true,qaAuditCount:result.qaAudits.length,qaRecordCounts:Object.fromEntries(Object.entries(result.qaRecords).map(([k,v])=>[k,v.length]))}));
}catch(e){console.log(JSON.stringify({safeError:e.code??e.constructor.name,safeColumn:e.code==='42703'?e.message:undefined}));process.exitCode=1;}finally{await client.end().catch(()=>{});}
